source "https://rubygems.org"

gem 'redis'
gem "lita"

# Uncomment to use the HipChat adapter
# gem "lita-hipchat"
gem 'redis'
gem "lita-discord_oauth"

gem 'lita-onewheel-garfield'
# Uncomment to use the IRC adapter
# gem "lita-irc"

# Add handlers to give Lita new functionality.
# For example:
 # gem "lita-google-images"
# gem "lita-karma"
